&nbsp;

# <center>Analysis Challenge Assignment 1</center>
### <center>Alex School Selction</center>
<center>Author: Simon Chen, Jianan Dingqian</center>
<center>Time: Sep 28, 2021</center>

#### **1. Criteria**

Alex wants to pursue a degree in Education. She wants to find the best school within U.S. with following requirements: <br>
1. Safety (low crime)
2. Urban (big city preferred)
3. Diversity (diverse culture)
4. Quality (decent program, but need to be defined)

#### **2. Tasks**

1. Create a dataset with limited information(e.g., crime rate, admission rate) to meet criteria.
2. Keep record of code and descriptions to explain designed approach.
3. Create a rule to rank the schools in consideration of all of Alex criteria taken together. (Bonus)

#### **3. Import**


###### a. Crime data

In [ ]:
# Import libraries.
import pandas as pd
# Reading the crime data in 2015 from shareable link into Pandas.
crime_data = pd.read_csv('https://raw.githubusercontent.com/lmaosimon/ColumbiaCourseProjects/main/HUDK%204050/Analysis%20Challenge%20Assignment%201/Crime_2015.csv')
# Convert numbers read as object into float
crime_data["ViolentCrime"]= crime_data["ViolentCrime"].str.replace(',', '').astype(float)
crime_data["PropertyCrime"]= crime_data["PropertyCrime"].str.replace(',', '').astype(float)
crime_data["Burglary"]= crime_data["Burglary"].str.replace(',', '').astype(float)
crime_data["Theft"]= crime_data["Theft"].str.replace(',', '').astype(float)
# Print data
crime_data

                                              MSA  ...         City
0                              Abilene, TX M.S.A.  ...      Abilene
1                                Akron, OH M.S.A.  ...        Akron
2                               Albany, GA M.S.A.  ...       Albany
3                               Albany, OR M.S.A.  ...       Albany
4                          Albuquerque, NM M.S.A.  ...  Albuquerque
..                                            ...  ...          ...
373                   Guayama, Puerto Rico M.S.A.  ...      Guayama
374                  Mayaguez, Puerto Rico M.S.A.  ...     Mayaguez
375                     Ponce, Puerto Rico M.S.A.  ...        Ponce
376                San German, Puerto Rico M.S.A.  ...   San German
377  San Juan-Carolina-Caguas, Puerto Rico M.S.A.  ...     San Juan

[378 rows x 12 columns]

###### b. College Scorecard data

In [ ]:
# Reading College Scorecard data in pandas df.
college_data = pd.read_csv('https://raw.githubusercontent.com/lmaosimon/ColumbiaCourseProjects/main/HUDK%204050/Analysis%20Challenge%20Assignment%201/CollegeScorecard.csv')
college_data

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (7,9,1427,1542,1561,1575,1725,1726,1727,1728) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

        UNITID    OPEID  ...  C200_L4_POOLED_SUPP C200_4_POOLED_SUPP
0       100654   100200  ...                  NaN   0.35168556430446
1       100663   105200  ...                  NaN    0.4730923834537
2       100690  2503400  ...                  NaN  PrivacySuppressed
3       100706   105500  ...                  NaN   0.49412939796716
4       100724   100500  ...                  NaN   0.29365162671232
...        ...      ...  ...                  ...                ...
7799  48285703   157107  ...                  NaN                NaN
7800  48285704   157101  ...                  NaN                NaN
7801  48285705   157105  ...                  NaN                NaN
7802  48285706   157100  ...                  NaN                NaN
7803  48285707   157103  ...                  NaN                NaN

[7804 rows x 1729 columns]

#### **4. Cleaning and Processing data**



###### a. Crime data

In [ ]:
# Then we rank the score to get a SafetyScore
# Since the reports number is the rates of reported offenses per 100,000 population.
# So we could just sum them up for each city to get the total rates by creating a new column rates.
crime_data['rates'] = crime_data.sum(axis=1)

# This table is now arranging cities from Hige crime rate to Low crime rate
crime_data = crime_data.sort_values(by='rates',ascending=False) 

# Then we rank the score to get a SafetyScore
safety_score=range(0,378)
crime_data['SafetyScore'] = safety_score

###### Extracting from the crime_data, we make a clean data. It's a new data frame called safety_score with MSA, state, city, and SafetyScore.

###### b. College Scorecard data

*Urban*